package com.telesure.fwa;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class claimInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("claimNumber")
	private java.lang.String claimNumber;
	@org.kie.api.definition.type.Label("claimAmount")
	private java.lang.Double claimAmount;
	@org.kie.api.definition.type.Label("claimType")
	private java.lang.String claimType;
	@org.kie.api.definition.type.Label("allocatedDate")
	private java.lang.String allocatedDate;

	@org.kie.api.definition.type.Label(value = "claimStatus")
	private java.lang.String claimStatus;

	@org.kie.api.definition.type.Label(value = "reportStatus")
	private java.lang.String reportStatus;

	public claimInfo() {
	}

	public java.lang.String getClaimNumber() {
		return this.claimNumber;
	}

	public void setClaimNumber(java.lang.String claimNumber) {
		this.claimNumber = claimNumber;
	}

	public java.lang.Double getClaimAmount() {
		return this.claimAmount;
	}

	public void setClaimAmount(java.lang.Double claimAmount) {
		this.claimAmount = claimAmount;
	}

	public java.lang.String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(java.lang.String claimType) {
		this.claimType = claimType;
	}

	public java.lang.String getAllocatedDate() {
		return this.allocatedDate;
	}

	public void setAllocatedDate(java.lang.String allocatedDate) {
		this.allocatedDate = allocatedDate;
	}

	public java.lang.String getClaimStatus() {
		return this.claimStatus;
	}

	public void setClaimStatus(java.lang.String claimStatus) {
		this.claimStatus = claimStatus;
	}

	public java.lang.String getReportStatus() {
		return this.reportStatus;
	}

	public void setReportStatus(java.lang.String reportStatus) {
		this.reportStatus = reportStatus;
	}

	public claimInfo(java.lang.String claimNumber,
			java.lang.Double claimAmount, java.lang.String claimType,
			java.lang.String allocatedDate, java.lang.String claimStatus,
			java.lang.String reportStatus) {
		this.claimNumber = claimNumber;
		this.claimAmount = claimAmount;
		this.claimType = claimType;
		this.allocatedDate = allocatedDate;
		this.claimStatus = claimStatus;
		this.reportStatus = reportStatus;
	}

}