package com.telesure.fwa;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class flowInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "userId")
	private java.lang.String userId;

	@org.kie.api.definition.type.Label(value = "decision")
	private java.lang.String decision;

	public flowInfo() {
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getDecision() {
		return this.decision;
	}

	public void setDecision(java.lang.String decision) {
		this.decision = decision;
	}

	public flowInfo(java.lang.String userId, java.lang.String decision) {
		this.userId = userId;
		this.decision = decision;
	}

}